# Generated by Django 2.0.4 on 2018-05-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarrageInfo',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_count', models.CharField(max_length=255)),
                ('barrage_text', models.CharField(max_length=255)),
                ('film_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CollectInfo',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('user_name', models.CharField(max_length=255)),
                ('film_name', models.CharField(max_length=255)),
                ('comment_text', models.CharField(max_length=1000)),
                ('comment_time', models.CharField(max_length=255)),
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FilmInfo',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(blank=True, max_length=255, null=True)),
                ('posters', models.CharField(blank=True, max_length=100, null=True)),
                ('grades', models.CharField(blank=True, max_length=100, null=True)),
                ('directors', models.CharField(blank=True, max_length=255, null=True)),
                ('writers', models.CharField(blank=True, max_length=500, null=True)),
                ('actors', models.CharField(blank=True, max_length=1000, null=True)),
                ('types', models.CharField(blank=True, max_length=255, null=True)),
                ('countrys', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('show_times', models.CharField(blank=True, max_length=255, null=True)),
                ('run_times', models.CharField(blank=True, max_length=255, null=True)),
                ('intros', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.CharField(blank=True, max_length=1000, null=True)),
                ('youku_urls', models.CharField(blank=True, db_column='YouKu_urls', max_length=255, null=True)),
                ('tengxun_urls', models.CharField(blank=True, db_column='TengXun_urls', max_length=255, null=True)),
                ('souhu_urls', models.CharField(blank=True, db_column='SouHu_urls', max_length=255, null=True)),
                ('aiqiyi_urls', models.CharField(blank=True, db_column='AiQiYi_urls', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZanOrCaiInfo',
            fields=[
                ('film_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('z_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
